# Generated by Django 3.2.25 on 2025-03-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='link',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
