# Generated by Django 3.2.25 on 2025-03-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_technology_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='career_path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.careerpath'),
            preserve_default=False,
        ),
    ]
