# Generated by Django 3.2.25 on 2025-03-10 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_technology_career_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='careers/'),
            preserve_default=False,
        ),
    ]
