# Generated by Django 3.2.25 on 2025-03-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_careerpath_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='career_path',
        ),
        migrations.RemoveField(
            model_name='course',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='CareerRecommendation',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
